/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Elder.Elder;
import Business.Elder.ElderBodyStatus;
import Business.Enterprise.NursingHouse;
import Business.Enterprise.NursingHouseDirectory;
import Business.NHSystem;
import Business.Network.Network;
import Business.UserAccount.AdministratorAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.ElderRole.bodyStatus;

/**
 *
 * @author cuijingyi
 */
public class bodyInfoStatisticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckRegisterJPanel
     */
    private JPanel container;
    private NHSystem system;
    private ArrayList<ElderBodyStatus> a;
    
    
    
    public bodyInfoStatisticsJPanel(JPanel container,NHSystem system) {
        initComponents();
        this.container = container;
        this.system=system; 
        populate();
         
    }
    

    public void refreshData(){
        populate();
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void populate(){
        DefaultTableModel dtm = (DefaultTableModel)tblApplication.getModel();
        dtm.setRowCount(0);
        int count1=0;
        int count2=0;
        int count3=0;
        for(Network network:system.getNetworkList()){
            for(NursingHouse nh:network.getNursingHouseDirectory().getNursingHouseList()){
                 for(Elder e:nh.getElderDirectory().getElderList()){
                 ArrayList<ElderBodyStatus> ebs = e.getElderBodyStatusDirectory().getBodystatusList();
                 
                 for(int i=0;i<ebs.size();i++){
                  Object[] row = new Object[dtm.getColumnCount()];
                  row[0] = ebs.get(i).getHeartRate();
                  if(ebs.get(i).getHeartRate()>75){
                      count3++;
                  }
                  row[1] = ebs.get(i).getBloodpressue();
                  if(ebs.get(i).getBloodpressue()<100){
                      count2++;
                  }
              
                  row[2] = ebs.get(i).getSpo2();
                  if(ebs.get(i).getSpo2()<95.5){
                      count1++;
                  }
                 dtm.addRow(row);
                 }
                     
                 }
                
                 }
            }
        jTextField2.setText(String.valueOf(count1));
        jTextField4.setText(String.valueOf(count3));
        jTextField3.setText(String.valueOf(count2));


    }
                
          
          
//    private void populateApplicationTable(){
//     DefaultTableModel model = (DefaultTableModel) tblApplication.getModel();
//        model.setRowCount(0);
//              for(Elder elder :system.getElderDirectory().getElderList()){
//                   for(ElderBodyStatus b:elder.getElderBodyStatusDirectory().getBodystatusList()) {
//                       Object[] row = new Object[5];
//                       for(int i=0;i<system.getNetworkList().size();i++){
//                           if(system.getNetworkList().get(i).equals(elder.getDirectory().findElderWithName(b.getOfWhichElder()).getNursingHouse())){
//                              row[0] = system.getNetworkList().get(i).getName();
//                           }
//                       }
//                       row[1] = elder.getName();
//                       row[2] = elder.getElderBodyStatusDirectory().searchElderBodyStatus(elder.getName()).getHeartRate();
//                       row[3] =elder.getElderBodyStatusDirectory().searchElderBodyStatus(elder.getName()).getBloodpressue();
//                       row[4] =elder.getElderBodyStatusDirectory().searchElderBodyStatus(elder.getName()).getSpo2();
//                       model.addRow(row);
//                   }     
//                
//            }
//              
//       }      
     

        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblApplication = new javax.swing.JTable();
        btnVA = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText(" Body Status Statistics");

        tblApplication.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "HeartRate", "BloodPressure", "Spo2"
            }
        ));
        jScrollPane1.setViewportView(tblApplication);

        btnVA.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        btnVA.setText("Count");
        btnVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVAActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("spo2 issues of all(>95.5):");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("bloodpressure issues of all(<100):");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("Heart issues of all(>75):");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVA, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVAActionPerformed
        // TODO add your handling code here:
        
//        int selectedRow = tblApplication.getSelectedRow();
//        if(selectedRow < 0){
//            JOptionPane.showMessageDialog(null,"Please select a row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);
//        }
//        else{
//         NursingHouse nursingHouse = (NursingHouse)tblApplication.getValueAt(selectedRow, 0);
//         ViewRegisterNursingHouseJPanel panel = new ViewRegisterNursingHouseJPanel(container,nursingHouse,system);
//         container.add(panel);
//         CardLayout cardlayout = (CardLayout) container.getLayout();
//         cardlayout.next(container);  
//        }
    }//GEN-LAST:event_btnVAActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tblApplication;
    // End of variables declaration//GEN-END:variables
}
