/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Enterprise.NursingHouse;
import Business.Enterprise.NursingHouseDirectory;
import Business.NHSystem;
import Business.Network.Network;
import Business.UserAccount.AdministratorAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cuijingyi
 */
public class CheckRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckRegisterJPanel
     */
    private JPanel container;
    private NursingHouseDirectory nd;
    private NursingHouse nh;
    private NHSystem system;
    
    
    public CheckRegisterJPanel(JPanel container,NursingHouseDirectory nd, NursingHouse nh,NHSystem system) {
        initComponents();
        this.container = container;
        this.nd = nd; 
        this.nh = nh;
        this.system=system;
         
        populateApplicationTable();
         
    }
    

    public void refreshData(){
        populateApplicationTable();
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void populateApplicationTable(){
     DefaultTableModel model = (DefaultTableModel) tblApplication.getModel();

        model.setRowCount(0);
              
              for(NursingHouse nursingHouse:system.getNursingHouseDirectory().getNursingHouseList()){
                     if(nursingHouse.getStatus()==0){
               for(AdministratorAccount aa : nursingHouse.getAdministratorAccountDirectory().getAdministratorAccountList()){
                      
                Object[] row = new Object[3];
                row[0] = nursingHouse;
                row[1] = aa.getAdministrator().getName();
                
                row[2] = nursingHouse.getStatus();
                model.addRow(row);
            }
                      }
                  
              
              }
       }      
     

        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblApplication = new javax.swing.JTable();
        btnVA = new javax.swing.JButton();

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Check  Registration");

        tblApplication.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nursing House Name", "Applicant Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblApplication);

        btnVA.setText("View Application");
        btnVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVA)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnBack)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnVA)
                .addContainerGap(226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVAActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblApplication.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select a row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
         NursingHouse nursingHouse = (NursingHouse)tblApplication.getValueAt(selectedRow, 0);
         ViewRegisterNursingHouseJPanel panel = new ViewRegisterNursingHouseJPanel(container,nursingHouse,system);
         container.add(panel);
         CardLayout cardlayout = (CardLayout) container.getLayout();
         cardlayout.next(container);  
        }
    }//GEN-LAST:event_btnVAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblApplication;
    // End of variables declaration//GEN-END:variables
}
