/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Enterprise.NursingHouse;
import Business.Enterprise.NursingHouseDirectory;
import Business.NHSystem;
import Business.Network.Network;
import Business.UserAccount.AdministratorAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cuijingyi
 */
public class ConclusionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckRegisterJPanel
     */
    private JPanel container;
    
    private NHSystem system;
     ArrayList bestList ;
     ArrayList worstList ;
    
    public ConclusionJPanel(JPanel container,NHSystem system) {
        initComponents();
        this.container = container;
       
        this.system=system;
         bestList = new ArrayList();
     worstList = new ArrayList();
         
    }
    
    private void populateBestTable(){
        DefaultTableModel model = (DefaultTableModel) bestTable.getModel();

        model.setRowCount(0);
              
              for(int i=0;i<bestList.size();i++){
                         
                Object[] row = new Object[3];
                row[0] = bestList.get(i);
                
                model.addRow(row);
            }
    }
    
    private void populateWorstTable(){
        DefaultTableModel model = (DefaultTableModel) bestTable.getModel();

        model.setRowCount(0);
              
              for(int i=0;i<worstList.size();i++){
                         
                Object[] row = new Object[3];
                row[0] = worstList.get(i);
                
                model.addRow(row);
            }
    }

    public void refreshData(){
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
     

        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVA = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVA1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bestTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        worstTable = new javax.swing.JTable();

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Uncomfortable Signs Statistics");

        btnVA.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnVA.setText("Analysis");
        btnVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVAActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("The network that the elder could have better health conditions:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("The net work that the elder may have more body issues: ");

        btnVA1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnVA1.setText("Make notifications");
        btnVA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVA1ActionPerformed(evt);
            }
        });

        bestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bestTable);
        if (bestTable.getColumnModel().getColumnCount() > 0) {
            bestTable.getColumnModel().getColumn(0).setResizable(false);
        }

        worstTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(worstTable);
        if (worstTable.getColumnModel().getColumnCount() > 0) {
            worstTable.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVA, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVA1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(btnBack)
                                    .addGap(125, 125, 125)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(172, 172, 172)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(26, 26, 26)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVA1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVAActionPerformed
        // TODO add your handling code here:
       
        
        int max = 0;
        for(int i = 0 ; i< system.getNetworkList().size();i++){
            if(i==0){
                max=system.getNetworkList().get(0).getUncomfortableAmount();
            }else{
          if(max < system.getNetworkList().get(i).getUncomfortableAmount()){
              max = system.getNetworkList().get(i).getUncomfortableAmount();
              //worstText.setText(system.getNetworkList().get(i).getName());
              //System.out.println(system.getNetworkList().get(i).getName());
          }
            } 
        }
        //System.out.println(max);
        for(int i=0;i<system.getNetworkList().size();i++){
            if(max==system.getNetworkList().get(i).getUncomfortableAmount()){
                worstList.add(system.getNetworkList().get(i).getName());
            }
        }
        
        
        int min = 0;
        for(int i = 1; i < system.getNetworkList().size();i++){
            if(i==0){
                system.getNetworkList().get(0).getUncomfortableAmount();
            }else{
         if(min > system.getNetworkList().get(i).getUncomfortableAmount()){
                min = system.getNetworkList().get(i).getUncomfortableAmount();
               // bestText.setText(system.getNetworkList().get(i).getName());
         }  
         //bestText.setText(system.getNetworkList().get(i).getName());
         }}
        
         for(int i=0;i<system.getNetworkList().size();i++){
            if(min==system.getNetworkList().get(i).getUncomfortableAmount()){
               bestList.add(system.getNetworkList().get(i).getName());
            }
        }
         //System.out.println (min);
         
         
         populateBestTable();
         populateWorstTable();
        
    }//GEN-LAST:event_btnVAActionPerformed

    private void btnVA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVA1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bestTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnVA;
    private javax.swing.JButton btnVA1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable worstTable;
    // End of variables declaration//GEN-END:variables
}
