/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministratorRole;

import Business.Administrator.Administrator;
import Business.Bed.Bed;
import Business.Elder.Elder;
import Business.Employee.Doctor;
import Business.Employee.NursingWorker;
import Business.Enterprise.NursingHouse;
import Business.NHSystem;
import Business.UserAccount.AdministratorAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author cuijingyi
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    private JPanel container;
    private Doctor doctor;
    private Elder elder;
    private NursingWorker nursingWorker;
    private NHSystem system;
    private AdministratorAccount aa;
    private String s;
    private String receiverIdentity;
    private String network;
   
    public AdminWorkAreaJPanel(JPanel container, NHSystem system, String s,AdministratorAccount aa,String network) {
        initComponents();
        this.container = container;
        this.system =system;
        this.s = s;
        this.aa=aa;
        this.network=network;
        //System.out.println(network);
      
        txtValue.setText(s);
        txtValue.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDoc = new javax.swing.JButton();
        btnNW = new javax.swing.JButton();
        btnElderlies = new javax.swing.JButton();
        btnBed = new javax.swing.JButton();
        btnAnalysis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        btnSN = new javax.swing.JButton();
        btnRN = new javax.swing.JButton();
        btnCP = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area ---- Administrator Role");

        btnDoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDoc.setText("Manage Doctors ");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        btnNW.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNW.setText("Manage Nursing Workers");
        btnNW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNWActionPerformed(evt);
            }
        });

        btnElderlies.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnElderlies.setText("Manage Elders");
        btnElderlies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElderliesActionPerformed(evt);
            }
        });

        btnBed.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBed.setText("Manage Beds");
        btnBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBedActionPerformed(evt);
            }
        });

        btnAnalysis.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAnalysis.setText("Analysis");
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nursing House:");

        btnSN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSN.setText("Send Notification");
        btnSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSNActionPerformed(evt);
            }
        });

        btnRN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRN.setText("Receive Notification");
        btnRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRNActionPerformed(evt);
            }
        });

        btnCP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCP.setText("Change Password");
        btnCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnElderlies, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNW, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnalysis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(241, 241, 241))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNW, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBed, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnElderlies, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        // TODO add your handling code here:
        ManageDocJPanel panel = new ManageDocJPanel(container,system,s);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);   
    }//GEN-LAST:event_btnDocActionPerformed

    private void btnNWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNWActionPerformed
        // TODO add your handling code here:
        ManageNWJPanel panel = new ManageNWJPanel(container,system,s);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);
    }//GEN-LAST:event_btnNWActionPerformed

    private void btnElderliesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElderliesActionPerformed
        // TODO add your handling code here:
        ManageEldersJPanel panel = new ManageEldersJPanel(container,system,s);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);
    }//GEN-LAST:event_btnElderliesActionPerformed

    private void btnBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBedActionPerformed
        // TODO add your handling code here:
        ManageBedsJPanel panel = new ManageBedsJPanel(container,system,s);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);
    }//GEN-LAST:event_btnBedActionPerformed

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        // TODO add your handling code here:
        AnalysisJPanel panel = new AnalysisJPanel(container,system,network);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);
    }//GEN-LAST:event_btnAnalysisActionPerformed

    private void btnSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSNActionPerformed
        // TODO add your handling code here:
        SendNotificationJPanel panel = new SendNotificationJPanel(container,s,receiverIdentity,aa,system);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);
    }//GEN-LAST:event_btnSNActionPerformed

    private void btnRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRNActionPerformed
        // TODO add your handling code here:
        ReceiveNotificationJPanel panel = new ReceiveNotificationJPanel(container,system,s,aa);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);
    }//GEN-LAST:event_btnRNActionPerformed

    private void btnCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPActionPerformed
        // TODO add your handling code here:
        ChangePasswordJPanel panel = new ChangePasswordJPanel(container,s,system);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);
    }//GEN-LAST:event_btnCPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnBed;
    private javax.swing.JButton btnCP;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnElderlies;
    private javax.swing.JButton btnNW;
    private javax.swing.JButton btnRN;
    private javax.swing.JButton btnSN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
