/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministratorRole;

import Business.Administrator.Administrator;
import Business.Bed.Bed;
import Business.Elder.Elder;
import Business.Employee.NursingWorker;
import Business.Enterprise.NursingHouse;
import Business.NHSystem;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

/**
 *
 * @author cuijingyi
 */
public class ManageBedsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageBedsJPanel
     */
    private JPanel container;
    private NHSystem system;
    private String s;
   // private Bed bed;
    public ManageBedsJPanel(JPanel container, NHSystem system, String s) {
        initComponents();
        btnAdd.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        btnBack1.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.lightBlue));
        btnDelete.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.red));
        this.container = container;
        this.system = system;
        this.s = s;
        txtNH.setText(s);
        txtNH.setEditable(false);
        populateBedTable();
     
    }
    

    public void refreshData(){
        this.populateBedTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void populateBedTable() {
        DefaultTableModel model = (DefaultTableModel) tblBed.getModel();

        model.setRowCount(0);
        for(Network network: system.getNetworkList()){
            for(NursingHouse nursingHouse : network.getNursingHouseDirectory().getNursingHouseList()){
                if(nursingHouse.getName().equals(s)){
                    for (Bed bed : nursingHouse.getBedList().getBedList()) {
            
                      Object[] row = new Object[3];
                      row[0] = bed;
                      row[1] = bed.getElderName();
                      row[2] = bed.getNursingWorkerName();
                
                      model.addRow(row);
           }
          }
         }
       }     
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBed = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBedNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNH = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setText("Manage   Beds  Information");

        btnBack1.setText("<<Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        tblBed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bed Number", "Elder Name", "Nursing Worker Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBed);
        if (tblBed.getColumnModel().getColumnCount() > 0) {
            tblBed.getColumnModel().getColumn(0).setResizable(false);
            tblBed.getColumnModel().getColumn(1).setResizable(false);
            tblBed.getColumnModel().getColumn(2).setResizable(false);
        }

        btnAdd.setText("Add New Bed");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Bed Information");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Bed Number:");

        txtBedNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBedNoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nursing House:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 180, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addGap(252, 252, 252))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(46, 46, 46)
                                            .addComponent(txtBedNo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                                .addGap(160, 160, 160))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack1)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(txtNH, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBedNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnAdd)
                .addGap(30, 30, 30)
                .addComponent(btnDelete)
                .addContainerGap(318, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        
        cardlayout.previous(container);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
            if(txtBedNo.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Please input bed number! ");
            }else{
        for(Network network: system.getNetworkList()){
            for(NursingHouse nursingHouse : network.getNursingHouseDirectory().getNursingHouseList()){
                if(nursingHouse.getName().equals(s)){ 
                    Bed bed = null;
                       for(Bed b : nursingHouse.getBedList().getBedList()){
                           if(Integer.parseInt(txtBedNo.getText()) == b.getBedId()){
                              bed=b;
                           } 
                }
                       if(nursingHouse.getBedList().getBedList().contains(bed)){
                           JOptionPane.showMessageDialog(null,"Bed has existed! ");
                       }else{
                              Bed d = nursingHouse.getBedList().addBed();
                              d.setElderName("Unknown");
                              d.setNursingWorkerName("Unkown");
                              d.setBedId(Integer.parseInt(txtBedNo.getText()));
                              JOptionPane.showMessageDialog(null,"Bed created successfully! ");
                       }
                    }
                }
            }}
        }
        
        catch(NumberFormatException nfe){
           JOptionPane.showMessageDialog(null,"BedId Only Numbers allowed");
       }
        txtBedNo.setText("");
        populateBedTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtBedNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBedNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBedNoActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBed.getSelectedRow();
        if (selectedRow >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the account details?", "Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Bed bed = (Bed)tblBed.getValueAt(selectedRow,0);
                
                for(Network network:system.getNetworkList()){
                    for(NursingHouse nursingHouse:network.getNursingHouseDirectory().getNursingHouseList()){
                        if(nursingHouse.getName().equals(s)){
                            for(Elder elder:nursingHouse.getElderDirectory().getElderList()){
                                if(elder.getBedId()==bed.getBedId()){
                                    elder.setBedId(0);
                                }
                            }
                        }
                    }
                }
                Bed be = null;
                for(Network network: system.getNetworkList()){
                    for(NursingHouse nh:network.getNursingHouseDirectory().getNursingHouseList()){
                        if(nh.getName().equals(s)){
                        for(Bed b : nh.getBedList().getBedList()){
                            if(b==bed){
                                be=b;
                            }
                        }
                        nh.getBedList().removeBed(be);
                        }
                        
                    }
                }
                //system.getBedList().removeBed(bed);
                populateBedTable();
            }
            else {
                JOptionPane.showMessageDialog(null,"Please select a row from table first","Warning",JOptionPane.WARNING_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblBed;
    private javax.swing.JTextField txtBedNo;
    private javax.swing.JTextField txtNH;
    // End of variables declaration//GEN-END:variables
}
