/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministratorRole;

import Business.NHSystem;
import Business.UserAccount.AdministratorAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

/**
 *
 * @author cuijingyi
 */
public class SendNotificationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SendNotificationJPanel
     */
    private JPanel container;
    private String s;
    private String receiverIdentity;
    private AdministratorAccount aa;
    private NHSystem system;
    public SendNotificationJPanel(JPanel container, String s,String receiverIdentity,AdministratorAccount aa,NHSystem system) {
        initComponents();
        btnBack.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.lightBlue));
        btnDoctor.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        btnElder.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        btnNW.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));

        this.container = container;
        this.s = s;
        this.receiverIdentity = receiverIdentity;
        this.aa = aa;
        this.system = system;
        txtNH.setText(s);
        txtNH.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnElder = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        btnNW = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNH = new javax.swing.JTextField();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Send  Notification");

        btnElder.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnElder.setText("Send A Notification To An Elder");
        btnElder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElderActionPerformed(evt);
            }
        });

        btnDoctor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDoctor.setText("Send A Notification To A Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        btnNW.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNW.setText("Send A Notification To A Nursing Worker");
        btnNW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNWActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nursing House:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnElder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnNW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNH, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnElder, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnNW, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(474, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnElderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElderActionPerformed
        // TODO add your handling code here:
        String receiverIdentity = "Elder";
        SendToAJPanel panel = new SendToAJPanel(container,s,receiverIdentity,aa,system);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);
    }//GEN-LAST:event_btnElderActionPerformed

    private void btnNWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNWActionPerformed
        // TODO add your handling code here:
        String receiverIdentity = "Nursing Worker";
        SendToAJPanel panel = new SendToAJPanel(container,s,receiverIdentity,aa,system);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);
    }//GEN-LAST:event_btnNWActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
        String receiverIdentity = "Doctor";
         SendToAJPanel panel = new SendToAJPanel(container,s,receiverIdentity,aa,system);
        container.add(panel);
        CardLayout cardlayout = (CardLayout) container.getLayout();
        cardlayout.next(container);
    }//GEN-LAST:event_btnDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnElder;
    private javax.swing.JButton btnNW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNH;
    // End of variables declaration//GEN-END:variables
}
