/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.NHSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Employee.Doctor;
import Business.Enterprise.NursingHouse;
import Business.Network.Network;
import Business.Notification.Notification;
import Business.Notification.NotificationDirectory;
import Business.Organization.Organization;
import Business.UserAccount.AdministratorAccount;
import Business.UserAccount.DoctorAccount;
import Business.UserAccount.ElderAccount;
import Business.UserAccount.NursingWorkerAccount;
import Business.UserAccount.SystemAdminAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.Background;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;
import sun.swing.ImageIconUIResource;
import userinterface.AdministratorRole.AdminWorkAreaJPanel;
import userinterface.Doctors.DoctorsJPanel;
import userinterface.ElderRole.chooseFunc;
import userinterface.NursingWorkers.ManageEldersJPanel;
import userinterface.NursingWorkers.NursingWorkersJPanel;
import userinterface.Register.RegisterNursingHouseJPanel;
import userinterface.Register.RegisterProcessJPanel;
import userinterface.SystemAdminWorkArea.SysAdminWorkAreaJPanel;

/**
 *
 * @author Lingfeng
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private NHSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    

    public MainJFrame() throws Exception {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        BeautyEyeLNFHelper.frameBorderStyle = BeautyEyeLNFHelper.FrameBorderStyle.generalNoTranslucencyShadow;
        loginJButton.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.red));
        logoutJButton.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.red));
        registerBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.lightBlue));
        org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
        UIManager.put("RootPane.setupButtonVisible", false);
        BeautyEyeLNFHelper.translucencyAtFrameInactive=true;
        this.setLocation(220,40);
        this.setSize(1000, 800); 
    }
    
    

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("User Name:");

        jLabel2.setText("Password:");

        logoutJButton.setText("Logout");
        logoutJButton.setEnabled(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        registerBtn.setText("Register Nursing House");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("/LJ的文件/Neu/Main20180902/5100+lab/NetBeansProjects/db4odemo_midterm5/admin-cut.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordField)
                    .addComponent(loginJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logoutJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(registerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(loginJLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(207, 207, 207)
                .addComponent(loginJButton)
                .addGap(18, 18, 18)
                .addComponent(logoutJButton)
                .addGap(18, 18, 18)
                .addComponent(registerBtn)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setLayout(new java.awt.CardLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("/LJ的文件/Neu/Main20180902/5100+lab/NetBeansProjects/db4odemo_midterm5/skilled-nursing-2.jpg")); // NOI18N
        container.add(jLabel4, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        RegisterProcessJPanel panel = new RegisterProcessJPanel(container,system,dB4OUtil);
        container.add("RegisterProcessJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        logoutJButton.setEnabled(false);
        userNameJTextField.setEnabled(true);
        passwordField.setEnabled(true);
        loginJButton.setEnabled(true);
        registerBtn.setEnabled(true);

        userNameJTextField.setText("");
        passwordField.setText("");

        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        container.updateUI();

        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // Get user name
        String userName = userNameJTextField.getText();
        // Get Password
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        if(userName.equals("Yanjuan")&&password.equals("333")){
            loginJButton.setEnabled(false);
            logoutJButton.setEnabled(true);
            registerBtn.setEnabled(false);

            userNameJTextField.setEnabled(false);
            passwordField.setEnabled(false);
            SysAdminWorkAreaJPanel panel = new SysAdminWorkAreaJPanel(container,system);
            container.add(panel);
            CardLayout cardlayout = (CardLayout)container.getLayout();
            cardlayout.next(container);
        }else{
            for(Network network:system.getNetworkList()){
                for(NursingHouse nursingHouse:network.getNursingHouseDirectory().getNursingHouseList()){
                    for(AdministratorAccount aa:nursingHouse.getAdministratorAccountDirectory().getAdministratorAccountList()){
                        if(aa==nursingHouse.getAdministratorAccountDirectory().authenticateAdministrator(userName, password)){

                            loginJButton.setEnabled(false);
                            logoutJButton.setEnabled(true);
                            registerBtn.setEnabled(false);

                            userNameJTextField.setEnabled(false);
                            passwordField.setEnabled(false);

                            AdminWorkAreaJPanel panel = new AdminWorkAreaJPanel(container,system,aa.getInstitution(),aa,network.getName());
                            container.add(panel);
                            CardLayout cardlayout = (CardLayout)container.getLayout();
                            cardlayout.next(container);

                        }else{
                            for(ElderAccount ea : nursingHouse.getElderAccountDirectory().getElderAccountList()){
                                if(ea==nursingHouse.getElderAccountDirectory().authenticateUser(userName, password)){

                                    chooseFunc cho=new chooseFunc(system, ea,ea.getInstitution());
                                    cho.setVisible(true);

                                    loginJButton.setEnabled(false);
                                    logoutJButton.setEnabled(true);
                                    registerBtn.setEnabled(false);

                                    userNameJTextField.setEnabled(false);
                                    passwordField.setEnabled(false);

                                }else{
                                    for(DoctorAccount da:nursingHouse.getDoctorAccountDirectory().getUserAccountList()){
                                        if(da==nursingHouse.getDoctorAccountDirectory().authenticateUser(userName, password)){

                                            DoctorsJPanel panel = new DoctorsJPanel(container,system,da.getInstitution(),da);
                                            container.add("ManageEldersJPanel",panel);
                                            CardLayout layout =(CardLayout)container.getLayout();
                                            layout.next(container);
                                            loginJButton.setEnabled(false);
                                            logoutJButton.setEnabled(true);
                                            registerBtn.setEnabled(false);

                                            userNameJTextField.setEnabled(false);
                                            passwordField.setEnabled(false);
                                        }else{
                                            for(NursingWorkerAccount nwa : nursingHouse.getNursingWorkerAccountDirectory().getNursingWorkerAccountList()){
                                                if(nwa==nursingHouse.getNursingWorkerAccountDirectory().authenticateUser(userName, password)){
                                                    loginJButton.setEnabled(false);
                                                    logoutJButton.setEnabled(true);
                                                    registerBtn.setEnabled(false);

                                                    userNameJTextField.setEnabled(false);
                                                    passwordField.setEnabled(false);

                                                    NursingWorkersJPanel panel = new NursingWorkersJPanel(container,nwa,nwa.getInstitution(),system);
                                                    container.add("NursingWorkersJPanel",panel);
                                                    CardLayout layout =(CardLayout)container.getLayout();
                                                    layout.next(container);
                                                }
                                            }
                                        }

                                    }
                                }
                            }
                        }

                    }
                }
            }

        }

    }//GEN-LAST:event_loginJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
