/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NursingWorkers;

import Business.NHSystem;
import Business.Notification.NotificationDirectory;
import Business.UserAccount.NursingWorkerAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

/**
 *
 * @author Liyanjuan
 */
public class NotificationTypeJPanel extends javax.swing.JPanel {

    private JPanel container;
    private NHSystem system;
    private NursingWorkerAccount nursingWorkerAccount;
   
    private String institution;
    /**
     * Creates new form NotificationTypeJPanel
     */
    public NotificationTypeJPanel(JPanel container, NursingWorkerAccount nursingWorkerAccount,String institution, NHSystem system) {
        initComponents();
        backBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.lightBlue));
        anAdminBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        anElderBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        this.container=container;
        this.system=system;
        this.nursingWorkerAccount=nursingWorkerAccount;
        
        this.institution=institution;
        nhText.setEditable(false);
        nhText.setText(institution);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anElderBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        anAdminBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nhText = new javax.swing.JTextField();

        anElderBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        anElderBtn.setText("Send Notification To Elder");
        anElderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anElderBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Send Notification");

        anAdminBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        anAdminBtn.setText("Send Notification To Administrator");
        anAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anAdminBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Nursing House:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(nhText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anElderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nhText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(anElderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(anAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(502, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void anElderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anElderBtnActionPerformed
        // TODO add your handling code here:
        NotificationToAPersonJPanel panel = new NotificationToAPersonJPanel(container,nursingWorkerAccount,institution,system,"Elder");
        container.add("NotificationToAPersonJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_anElderBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void anAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anAdminBtnActionPerformed
        // TODO add your handling code here:
        NotificationToAPersonJPanel panel = new NotificationToAPersonJPanel(container,nursingWorkerAccount,institution,system,"Administrator");
        container.add("NotificationToAPersonJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_anAdminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anAdminBtn;
    private javax.swing.JButton anElderBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nhText;
    // End of variables declaration//GEN-END:variables
}
