/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NursingWorkers;

import Business.NHSystem;
import Business.Notification.NotificationDirectory;
import Business.UserAccount.NursingWorkerAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

/**
 *
 * @author Liyanjuan
 */
public class NursingWorkersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NursingWorkersJPanel
     */
    private JPanel container;
    private NursingWorkerAccount nursingWorkerAccount;
    private String institution;
    private NHSystem system;
    
    
    public NursingWorkersJPanel(JPanel container,NursingWorkerAccount nursingWorkerAccount,String institution,NHSystem system) {
        initComponents();
        manageBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.lightBlue));
        modifyBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.red));
        notificationBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        receiveBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        this.container=container;
        this.nursingWorkerAccount=nursingWorkerAccount;
        this.institution=institution;
        this.system=system;
        nhText.setText(institution);
        nhText.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageBtn = new javax.swing.JButton();
        modifyBtn = new javax.swing.JButton();
        notificationBtn = new javax.swing.JButton();
        receiveBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nhText = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Home Page (Nursing Workers)");

        manageBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        manageBtn.setText("Manage Elders");
        manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBtnActionPerformed(evt);
            }
        });

        modifyBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        modifyBtn.setText("Modify Personal Information");
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });

        notificationBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        notificationBtn.setText("Send Notification");
        notificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBtnActionPerformed(evt);
            }
        });

        receiveBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        receiveBtn.setText("Received Notifications");
        receiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Nursing House:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52)
                                .addComponent(nhText))
                            .addComponent(modifyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notificationBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(receiveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nhText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addComponent(manageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(modifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(notificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(receiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void manageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBtnActionPerformed
        // TODO add your handling code here:
        ManageEldersJPanel panel = new ManageEldersJPanel(container,nursingWorkerAccount,institution,system);
        container.add("ManageEldersJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
        

    }//GEN-LAST:event_manageBtnActionPerformed

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        // TODO add your handling code here:
        ModifyPersonalInformationJPanel panel = new ModifyPersonalInformationJPanel(container,nursingWorkerAccount,institution);
        container.add("ModifyPersonalInformationJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_modifyBtnActionPerformed

    private void notificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBtnActionPerformed
        // TODO add your handling code here:
        NotificationTypeJPanel panel = new NotificationTypeJPanel(container,nursingWorkerAccount,institution,system);
        container.add("NotificationTypeJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_notificationBtnActionPerformed

    private void receiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveBtnActionPerformed
        // TODO add your handling code here:
        
        ReceivedNotificationsJPanel panel = new ReceivedNotificationsJPanel(container,nursingWorkerAccount,system,institution);
        container.add("ReceivedNotificationsJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_receiveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageBtn;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JTextField nhText;
    private javax.swing.JButton notificationBtn;
    private javax.swing.JButton receiveBtn;
    // End of variables declaration//GEN-END:variables
}
