/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctors;

import Business.NHSystem;
import Business.UserAccount.DoctorAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

/**
 *
 * @author Liyanjuan
 */
public class DoctorsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorsJPanel
     */
    private JPanel container;
    private NHSystem system;
    private String institution;
    private DoctorAccount doctorAccount;
    
    public DoctorsJPanel(JPanel container, NHSystem system, String institution,DoctorAccount doctorAccount) {
        initComponents();
        manageBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.lightBlue));
        receivedNotificationBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.red));
        receivedNotificationBtn1.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        personalInfoBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        this.container = container;
        this.system = system;
        this.institution=institution;
        this.doctorAccount=doctorAccount;
        nhText.setEditable(false);
        nhText.setText(institution);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageBtn = new javax.swing.JButton();
        receivedNotificationBtn = new javax.swing.JButton();
        receivedNotificationBtn1 = new javax.swing.JButton();
        personalInfoBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nhText = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Home Page (Doctors)");

        manageBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        manageBtn.setText("Manage Cases");
        manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBtnActionPerformed(evt);
            }
        });

        receivedNotificationBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        receivedNotificationBtn.setText("Received Notifications");
        receivedNotificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedNotificationBtnActionPerformed(evt);
            }
        });

        receivedNotificationBtn1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        receivedNotificationBtn1.setText("Send Notification");
        receivedNotificationBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedNotificationBtn1ActionPerformed(evt);
            }
        });

        personalInfoBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        personalInfoBtn.setText("Modify Personal Information");
        personalInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalInfoBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Nursing House:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receivedNotificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receivedNotificationBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personalInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 24, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(58, 58, 58)
                                .addComponent(nhText)))))
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nhText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(manageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(receivedNotificationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(receivedNotificationBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(personalInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBtnActionPerformed
        // TODO add your handling code here:
        ManageCasesJPanel panel = new ManageCasesJPanel(container,system,institution,doctorAccount);
        container.add("ManageEldersJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_manageBtnActionPerformed

    private void receivedNotificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedNotificationBtnActionPerformed
        // TODO add your handling code here:
        ReceivedNotificationsJPanel panel = new ReceivedNotificationsJPanel(container,system,institution,doctorAccount);
        container.add("ReceivedNotificationsJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_receivedNotificationBtnActionPerformed

    private void receivedNotificationBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedNotificationBtn1ActionPerformed
        // TODO add your handling code here:
        NotificationTypeJPanel panel = new NotificationTypeJPanel(container,system,institution,doctorAccount);
        container.add("NotificationTypeJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_receivedNotificationBtn1ActionPerformed

    private void personalInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalInfoBtnActionPerformed
        // TODO add your handling code here:
         ModifyPersonalInfoJPanel panel = new ModifyPersonalInfoJPanel(container,system,institution,doctorAccount);
        container.add("SendNotificationJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_personalInfoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageBtn;
    private javax.swing.JTextField nhText;
    private javax.swing.JButton personalInfoBtn;
    private javax.swing.JButton receivedNotificationBtn;
    private javax.swing.JButton receivedNotificationBtn1;
    // End of variables declaration//GEN-END:variables
}
