/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Doctors;

import Business.NHSystem;
import Business.UserAccount.DoctorAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

/**
 *
 * @author Liyanjuan
 */
public class NotificationTypeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotificationTypeJPanel
     */
    private JPanel container;
    private NHSystem system;
    private String receiverIdentity;
    private DoctorAccount doctorAccount;
    private String institution;
    
    public NotificationTypeJPanel(JPanel container,NHSystem system,String institution, DoctorAccount doctorAccount ) {
        initComponents();
        backBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.lightBlue));
        elderBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        administratorBtn.setUI(new BEButtonUI().setNormalColor(BEButtonUI.NormalColor.green));
        this.container=container;
        this.system=system;
        this.doctorAccount=doctorAccount;
        this.institution=institution;
        nhText.setEditable(false);
        nhText.setText(institution);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        elderBtn = new javax.swing.JButton();
        administratorBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nhText = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Send Notification");

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        elderBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        elderBtn.setText("Send Notification To Elder");
        elderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elderBtnActionPerformed(evt);
            }
        });

        administratorBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        administratorBtn.setText("Send Notification To Administrator");
        administratorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administratorBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Nursing House:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(administratorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(212, 212, 212))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(backBtn)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(nhText, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nhText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(elderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(administratorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(523, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnActionPerformed

    private void elderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elderBtnActionPerformed
        // TODO add your handling code here:
        SendNotificationJPanel panel = new SendNotificationJPanel(container,system,"Elder",institution,doctorAccount);
        container.add("SendNotificationJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_elderBtnActionPerformed

    private void administratorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administratorBtnActionPerformed
        // TODO add your handling code here:
         SendNotificationJPanel panel = new SendNotificationJPanel(container,system,"Administrator",institution,doctorAccount);
        container.add("SendNotificationJPanel",panel);
        CardLayout layout =(CardLayout)container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_administratorBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administratorBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton elderBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nhText;
    // End of variables declaration//GEN-END:variables
}
